version: '3.5'

services:
    database_keep_app:
        image: postgres
        container_name: database_keep_app
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: keep_app
        volumes:
            - database_keep_app_data:/data/postgres
        #/var/lib/postgresql/data/

    keep_api:
        build: ./api
        container_name: keep_api
        ports:
            - 3333:3333
        volumes:
            - ./api:/usr/app

volumes:
    database_keep_app_data:
        driver: local